name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af68
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@2500896c2bc0b2d37a5a4d41a3f9c7a04b01daf
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.organization=hugo-menes
            -Dsonar.projectKey=Hugo_Meneses_Moreno_TattaPizzaV2
            -Dsonar.sources=artifacts
            -Dsonar.exclusions=**/node_modules/**,**/dist/**